Stop building distributions for standalone Tomcat
FDA-MyStudies/UserReg-WS pull request #160
Opened 2024-08-14 21:17 UTC by labkey-adam

#### Rationale
We no longer support standalone Tomcat

#### Related Pull Requests
* https://github.com/LabKey/distributions/pull/473

2024-08-15 17:42 UTC, labkey-tchad approved these changes

2024-08-15 18:39 UTC, labkey-tchad requested changes
The tests on TeamCity indicate that `ResponseAction` isn't throwing errors correctly when running embedded; they have the correct response code but don't include an error message, just the generic "Bad Request".

2024-08-15 19:29 UTC, labkey-adam commented
> The tests on TeamCity indicate that `ResponseAction` isn't throwing errors correctly when running embedded; they have the correct response code but don't include an error message, just the generic "Bad Request".

`RegisterAction`, right? I'll take a look.

2024-08-20 00:25 UTC, labkey-adam commented
@labkey-tchad I suggest we merge this PR since 1) fairly certain it's not related to the test failure and 2) we're likely to fix that problem on 24.7

2024-08-20 20:25 UTC, labkey-tchad approved these changes

2024-08-20 20:44 UTC, merged